// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//             'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//   //
//   // static const FirebaseOptions android = FirebaseOptions(
//   //   apiKey: 'AIzaSyCn9hrEymzTDK1zFqZQkVFvk_MRlumOdSE',
//   //   appId: '1:213123394206:android:6ad30b3d99775aae5d298f',
//   //   messagingSenderId: '213123394206',
//   //   projectId: 'wallpaper-ab1f2',
//   //   storageBucket: 'wallpaper-ab1f2.appspot.com',
//   // );
//   //
//
//
//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyAHosYbYqwJOnkR7gGeRK1fUBllwiAI-XU',
//   //   appId: '1:218038339031:ios:e1185039161bc77a5a3792',
//   //   messagingSenderId: '213123394206',
//   //   projectId: 'wallpaper-ab1f2',
//   //   storageBucket: 'wallpaper-ab1f2.appspot.com',
//   //   iosClientId: '213123394206-2u29p3el125ahlebffbhk6tsiaoprhov.apps.googleusercontent.com',
//   //   iosBundleId: 'com.ihs.smsapp',
//   // );
//
//
//
//   static const FirebaseOptions android = FirebaseOptions(
//
//
//      apiKey: "AIzaSyDLNYFY8RJeLMfas2OhlzHjYqsQlxfy2gQ",
//   projectId: "python-412bf",
//   storageBucket: "python-412bf.appspot.com",
//   messagingSenderId: "218038339031",
//   appId: "1:218038339031:web:cd23ec01e746212e5a3792",
//
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDLNYFY8RJeLMfas2OhlzHjYqsQlxfy2gQ',
//     appId: '1:218038339031:web:cd23ec01e746212e5a3792',
//     messagingSenderId: 'G-N267PNFZPT',
//     projectId: 'python-412bf'
//
// );
//
// }
